### ISSUE TITLE
To do before we reach out to usability eval participants

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/scpca-nf#161]
Email Drafts
- [x] Invite email
- [x] Email providing info for session 2
- [x] Follow-up email for scheduling (maybe we can play this by ear?) 
- [x] Confirmation email for session 2 - provide info about what to expect (will have to share their desktop) 
- [x] Diary study email 

Other UX items:
- [x] UXR Consent Template
- [x] Diary study questions + form 

Issues
- [x] #156 
- [x] #157 
- [x] #158 
- [x] #159 

Please add any other issues that need to be done before we reach out to people
